### ISSUE TITLE
OverlayPanel: open position bug

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#1579]
Sometimes the OverlayPanel opens crookedly, either off-screen, or not near the clicked point.

Light codesandbox example
https://codesandbox.io/embed/beautiful-engelbart-ss1q0?fontsize=14&hidenavigation=1&theme=dark

Try to place the button on all 4 sides and look at the behavior, in my project OverlayPanel often opens incorrectly and I have to scroll the page

![image](https://user-images.githubusercontent.com/16963395/134294359-45ec6152-1263-4731-8f63-8204a791e121.png)

![image](https://user-images.githubusercontent.com/16963395/134294681-ae7c4f5f-2802-4c43-8f65-0a215e311d16.png)

![image](https://user-images.githubusercontent.com/16963395/134294587-f0b37605-8cf1-4258-9a11-fb87e929eaef.png)

**Comment by NeluQi** [comment]
PS - The second screenshot is a way out of the bottom border of the browser

**Comment by mertsincan** [comment]
Hi @NeluQi, 

Unfortunately, I still couldn't replicate this issue. What step do I need to follow to replicate it? Could you please update codesandbox link according to your case? 

Thanks a lot!

**Comment by NeluQi** [comment]
> Hi @NeluQi,
> 
> Unfortunately, I still couldn't replicate this issue. What step do I need to follow to replicate it? Could you please update codesandbox link according to your case?
> 
> Thanks a lot!

![image](https://user-images.githubusercontent.com/16963395/141603677-f5c2d56b-092b-45a6-abe0-2b59a40d2500.png)

https://codesandbox.io/embed/mystifying-silence-2rdhw?fontsize=14&hidenavigation=1&theme=dark
I tried to reproduce it now and I'm not good at it

Now the problem occurs much less frequently. May have already been fixed in new versions.

I was able to reproduce strange behavior sometimes

Try it in different combinations with scrolling and dialogue in different parts of the screen

It seems that this is not particularly relevant now, the bug is very rare

**Comment by mertsincan** [comment]
Hi @NeluQi,
Thanks a lot for the sample and detailed explanations! I'm pushing this issue to the next version for now. Looks like we need to run a lot of tests related to OverlayPanel.

Best Regards,

**Comment by NeluQi** [comment]
In my project, the panel arrow is shifted.

I spent a bunch of time doing this in a sandbox but could not reproduce

I found out that in my project, this only happens with the right panel opening

This is strange because the css is standard, I only replaced the colors

This panel doesn't look its best on mobile.

BUG:
![image](https://user-images.githubusercontent.com/16963395/146316281-0a02e892-aa9e-443a-b8b5-6dc413381248.png)

GOOD:
![image](https://user-images.githubusercontent.com/16963395/146316367-3e1857af-1710-4e92-953f-46b57b910be3.png)

**Comment by martinszeltins** [comment]
This is still an issue, I was able to reproduce the bug on PrimeVue docs themselves:

https://user-images.githubusercontent.com/34019878/223940310-314393dc-7dcc-499f-a6ec-d1d3043443f6.mp4

**Comment by JediPixels** [comment]
Still an issue with my app too... It looks like if the button calling is located towards the right side of the page and with width of the Popover is fairly large, the Point Arror portion is to the left side of the Popover, but it should be on the right side under the calling button.
