### ISSUE TITLE
Multiselect: Menu closes on select

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#4861]
### Describe the bug

I want to display the selected options at the top of the list.
I therefore sort the selected options to the top.

If I now click on something further down in the menu, it is automatically sorted to the top.
At the same time, the menu closes by mistake. The menu should remain open.

Cause of the error:
Since I use the virtualscroller, not all options are rendered in the html.
Therefore the outsideClickListener does not find the clicked option and thinks it was a click outside the menu.
The menu is then incorrectly closed.

### Reproducer

https://stackblitz.com/edit/lictaz?file=src%2FApp.vue

### PrimeVue version

3.41.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

Open Menu
Scroll Down
Select an option
=> Menu will close

### Expected behavior

Menu should stay open as long as I dont click outside.

**Comment by dy-xiaodong2022** [comment]
You don't need to add to much options, just need to scroll and select then the problem can reproduce.
```
Array.from({ length: 10 }, (_, i) => ({ name: `City #${i}`, id: i }))
```

**Comment by dy-xiaodong2022** [comment]
This problem is caused by `components/lib/multiselect/MultiSelect.vue -> default.methods.onContainerClick`
```javascript
onContainerClick(event) {
    if (this.disabled || this.loading) {
        return;
    }
    if (!this.overlay || !this.overlay.contains(event.target)) {
        this.overlayVisible ? this.hide(true) : this.show(true);
    }
},
```
The `this.overlay.contains(event.target)` in if expression should have some change.

**Comment by MaXal** [comment]
Simple reproducer: https://stackblitz.com/edit/hmwkta?file=src/App.vue,package.json

```
<template>
  <div class="card flex justify-content-center">
    <MultiSelect
      v-model="selectedCities"
      :options="cities"
      optionLabel="name"
      placeholder="Select Cities"
      :maxSelectedLabels="3"
      class="w-full md:w-20rem"
    />
  </div>
</template>

<script setup>
import { computed, ref } from "vue"

const selectedCities = ref()

const cities = computed(() => {
  const cities = ref([
    { name: "New York", code: "NY" },
    { name: "Rome", code: "RM" },
    { name: "London", code: "LDN" },
    { name: "Istanbul", code: "IST" },
    { name: "Paris", code: "PRS" },
  ])
  return cities.value.sort((a, b) => {
    if (selectedCities.value.includes(a)) return -1
    if (selectedCities.value.includes(b)) return 1
    return 0
  })
})
</script>

```

**Comment by dy-xiaodong2022** [comment]
I’ve tested #4864 and this pr should fix this issue.

**Comment by tugcekucukoglu** [comment]
Cannot replicate issue with the latest version. How can replicate the issue?

**Comment by tugcekucukoglu** [comment]
You could try to add a theme and if you prefer unstyled mode, `unstyled` prop should be added to the component. Otherwise, outside click implementation will not work as expected.

**Comment by MaXal** [comment]
I've updated the example using the theme and the issue is still there: https://stackblitz.com/edit/ivkrzp?file=src%2FApp.vue

![2024-07-01 18 46 34](https://github.com/primefaces/primevue/assets/266747/b43dd011-eed5-4f02-822d-13027cdeb226)

**Comment by philippmerz** [comment]
i have the same issue, also with theme @tugcekucukoglu

**Comment by koshik34** [comment]
me too

**Comment by MaXal** [comment]
@tugcekucukoglu Could you please reopen the issue and maybe merge the fix https://github.com/primefaces/primevue/pull/5656? 🙏
