### ISSUE TITLE
Form: API Loaded data not passing to $form.[field].value

### ISSUE THREAD

**Issue by magicMustard** [primefaces/primevue#6801]
### Describe the bug

I have an issue where I am attempting to populate the fields from an API. However, the data is not going through to the $form data object.

There is this bug here: https://github.com/primefaces/primevue/issues/6755 - Not sure if it'll solve my issue, however, if it does, I'll wait till it's released.

So, essentially, in the onMounted, it is getting the data from the API and populating to the initialValues, however when this is done, it does not appear to be passing to the input fields.

If I add a v-model="initialValues.first_name", this kinda works. Where the data populates, but if you hit the submit button, it throws field errors saying it's required, because the value in the $form.first_name.value has not been populated.

Am I doing it incorrectly or is this an issue that might be resolved from this bug?

Here is my code (stripped out the non important parts):
```vue
<template>
	<Form v-slot="$form" :initialValues :resolver @submit="onFormSubmit">
		<AppField :label="t('profiles.firstName')" name="first_name" :fieldState="$form.first_name">
			<InputText name="first_name" />
		</AppField>
		<AppField :label="t('profiles.lastName')" name="last_name" :fieldState="$form.last_name">
			<InputText name="last_name" />
		</AppField>

		<AppSubmit :create="!id" />
	</Form>
</template>

<script setup lang="ts">

const props = defineProps<{
	id?: string;
}>()

// Initial values for the form
const initialValues = ref({
	first_name: '',
	last_name: ''
});

onMounted(async () => {
	if (props.id) {
		const { data, error } = await supabase.from('profiles').select('first_name, last_name').eq('id', props.id).single();

		if (error) {
			console.error('error', error);
			return;
		}

		initialValues.value = data;
	}
});
</script>
```

### Reproducer

https://stackblitz.com/edit/wafqr9?file=src%2FApp.vue

### PrimeVue version

4.2.2

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Firefox 132.0.1 - Fedora

### Steps to reproduce the behavior

1. Create a form with input fields
2. add the v-slot="$form" to the Form and add a InputText, or anything
3. Add the expected script data, you can use the stackblitz as an example https://stackblitz.com/edit/wafqr9?file=src%2FApp.vue
4. Add a timeout to populate some data after it's loaded
5. You'll notice the data is not loading into the form.

### Expected behavior

It should populate the input fields with the data as you'd expect if you were to use v-model.

**Comment by Yonaro** [comment]
I have the same issue using the zod resolver. When the form is used to create, it works. But forms are not used only for the initial creation of a record.  Forms are also used for mutating existing records. I agree with magicMustard the standard vuejs v-modle design should be kept.

**Comment by magicMustard** [comment]
Thanks for the update. We moved onto formkit in the meantime. If it gets fixed, we'll come back and review.

**Comment by naumanahmed19** [comment]
I am also stuck on this issue. it should be fixed. it works with use of v-if until server data is loading. but not mutating values as expected.

**Comment by wiifree** [comment]
I agree with @naumanahmed19 
It should be no problem to change values after the form was initialized. I'm also stuck in this issue.

**Comment by ljgazzano** [comment]
same issue. Any solution??

**Comment by raizdev** [comment]
with onBeforeMount it works fine... @magicMustard

**Comment by magicMustard** [comment]
> with onBeforeMount it works fine... @magicMustard

That would make sense. Something I didn't consider, have moved onto another solution in the meantime. Having said this, still doesn't resolve the underlying issue.

**Comment by mertsincan** [comment]
Hello,

In 4.3.0 (next version), I added `setFieldValue(name, value);` and `setValues(nameValueObject)` to set new values to fields. The initialValue can only be set before the component is mounted. 

Exp;
```
formRef.setValues({
    username: "fred"
    email: "fred@ferd.com"
});

Or

formRef.setFieldValue('username', 'fred');
...
```

Best Regards,

**Comment by allansun** [comment]
I'm eagerly awaiting the release of this feature. My upcoming project involves using PrimeVue, and I've been grappling with this issue for two days. It's hard to believe that such a well-established project lacks this feature. I'm quite curious about how others managed to get it working, especially when it comes to updating pre-existing data loaded from a database.

**Comment by wiifree** [comment]
@mertsincan 
can you say approximately when 4.3.0 will be released?

**Comment by mertsincan** [comment]
@wiifree, we plan to release it this week.

**Comment by Milos5611** [comment]
@mertsincan do you have some info on when we can get the 4.3.0? This doesn't work and workarounds are inconvenient

**Comment by matheussantiago02** [comment]
@mertsincan any updates on when this version will be released?

**Comment by raizdev** [comment]
@mertsincan any updates for the newest release? I'm stuck at the moment to set new values after dom is loaded

**Comment by Milos5611** [comment]
I'm moving to another library, this is very frustrating and irritating. The maintainer posted a comment that they had a fix for one huge problem a month ago and ever since he has not responded. For whoever is reading this, don't use this library in your production application!

**Comment by alexlazebwork** [comment]
@mertsincan could you clarify, how can i access formRef?

**Comment by impcyber** [comment]
@alexlazebwork 
```ts
...
const formRef = ref<typeof Form>()
...
```
```html
<Form ref="formRef" ...
```

**Comment by Koishiiko** [comment]
I spent over an hour rereading the [documentation](https://primevue.org/forms) and failing countless times before realizing that the `Form` seems to internally maintain its own data rather than directly using `initial-values` itself. This is highly counterintuitive.

Why not simply use something like `<Form v-model="formData">` instead? That way, it wouldn't only read initial-values when the component mounted.

For now, this is how I’ve temporarily solved this issue, but I hope there’s a better solution:

```vue
<Form v-if="data != null" :initial-values="data">
    <!-- ... -->
</Form>
```

**Comment by vitaliykoreev** [comment]
I'm still having this issue on 4.3.1, but I'm fixed it with ref and "reset" method.

1. Add ref to the form
`<Form v-slot="$form" ref="form" :initialValues :resolver @submit="onSubmit">`

2. Create ref in your setup
`const form = ref();`

3. Use reset method when async data is loaded
`onMounted(() => {
    ProfileService.get().then((response) => {
        initialValues.first_name = response.data?.first_name;

        form.value?.reset();
    });
});`

**Comment by evsar3** [comment]
In my case it seems to be related to the InputText component, all other components (InputMask, Select etc.) seems to get it form state updated from the prop `initialValues`. To address the issue I had to update the form state myself:

```vue
<script lang="ts" setup>
import { ref, onMounted } from 'vue'
import { useMyStore } from '@/stores/my-store'

const myStore = useMyStore()

// ref<typeof Form> did not work because the Form component type
// does not expose its methods and properties
const $form = ref<any>(null)

const initialValues = ref<Record<string, any>>({})

onMounted(async () => {
    initialValues.value = await myStore.load()

    // Iterate over the initial values and set the form state values
    Object.entries(initialValues.value).forEach(([key, value]) => {
      if ($form.value?.states[key]) {
        try {
          $form.value.states[key].value = value
        } catch {}
      }
    })
})
</script>

<template>
  <Form ref="$form" v-slot="$form" :initialValues="initialValues">
    ...
  </Form>
</template>
```

This is indeed very annoying and I'm hopping for the maintainers to get some time to dig into this and make it work seemly.

Hope this helps. 😉

**Comment by starredev** [comment]
@mertsincan initialValues is hard to work with, if you trying to fetch async. could you please look into it?

**Comment by linoiris** [comment]
Came here with this exact issue. Seems it is still unresolved, will fall back to FormKit for now.

**Comment by linoiris** [comment]
> I'm moving to another library, this is very frustrating and irritating. The maintainer posted a comment that they had a fix for one huge problem a month ago and ever since he has not responded. For whoever is reading this, don't use this library in your production application!

Which library did you decide to move to?

**Comment by linoiris** [comment]
> > > I'm moving to another library, this is very frustrating and irritating. The maintainer posted a comment that they had a fix for one huge problem a month ago and ever since he has not responded. For whoever is reading this, don't use this library in your production application!
> > 
> > 
> > [@Milos5611](https://github.com/Milos5611) Which library did you decide to move to?
> 
> I went with Formik. It's not robust as Formik for React but at least it does the things. I can manipulate the form data however i want.

@Milos5611 Thanks, I'm looking into that as well. Used it for a dynamic form, worked great. Question: do you have a solution for  hiding the error messages under fields?

**Comment by starredev** [comment]
> > I'm moving to another library, this is very frustrating and irritating. The maintainer posted a comment that they had a fix for one huge problem a month ago and ever since he has not responded. For whoever is reading this, don't use this library in your production application!
> 
> [@Milos5611](https://github.com/Milos5611) Which library did you decide to move to?

Reglejs

**Comment by wiifree** [comment]
@linoiris 

For me, the problem is solved. Here is a example:

Define the Form with a ref:
```
<Form ref="testForm">
```
and with this you can set the values
```
const testForm = useTemplateRef<FormInstance>('testForm');
watch(testForm, async () => {
	if (testForm.value) {
		testForm.value.setValues({
			field1: value1
		});
	}
});

```

**Comment by yawaweb** [comment]
For me this works:

`  
Object.entries(formValues).forEach(([key, value]) => {
    formRef.value.setFieldValue(key, value);
  });
`

formRef.value.setValues doesn't work in my case.

**Comment by marciomdrs2002** [comment]
Same problem here. I need to use the initialValues to edit them, but the Form component doens't work as v-model behaviour

**Comment by linoiris** [comment]
I went with FormKit for the forms I need to manipulate. It’s really good. And there is a PrimeVue skin you can apply (forgot the name, just google it).FormKit is awesome, I have some forms that I need to build based on selections by the user and it works wonderfully.Sent from my iPhone. Please excuse brief replies.On Jun 17, 2025, at 03:13, Marcio de Medeiros ***@***.***> wrote:﻿marciomdrs2002 left a comment (primefaces/primevue#6801)
Same problem here. I need to use the initialValues to edit them, but the form component doens't work as v-model behaviour

**Comment by ColiZei** [comment]
I used this approach with zod and i works for now:

```vue
<script setup lang="ts">
// ...

const data = useDataStore();

const initialValues = ref<DataDto>({
  foo: "",
});

const resolver = createZodResolver(dataSchema);

const form = useTemplateRef<FormInstance>("form");


const onFormSubmit = async (event: FormSubmitEvent) => {
  console.log("Submit!", event);
};

onMounted(async () => {
  await data.fetchData();

  if (data.formData) {
    form.value?.setValues(data.formData);
  }
});
</script>

<template>
 <!-- ... -->
    <Form
      ref="form"
      v-slot="$form"
      :initial-values="initialValues"
      :resolver="resolver"
      @submit="onFormSubmit"
    >
     <!-- ... -->
      <PVInputText
        id="foo"
        name="foo"
        type="text"
      />
     <!-- DEBUG -->
      {{ $form.foo }}
      <PVMessage
        v-if="$form.foo?.invalid"
        severity="error"
        size="small"
        variant="simple"
      >
        {{ $t($form.foo.error.message) }}
      </PVMessage>
    </Form
 <!-- ... -->
</template>
```
