### ISSUE TITLE
DataTable: Reorder feature is broken

### ISSUE THREAD

**Issue by liuchunlei-jpg** [primefaces/primevue#7341]
### Describe the bug

DataTable Reorder feature on the official website is broken
https://primevue.org/datatable/#reorder

### Reason for not contributing a PR

- [ ] Lack of time
- [ ] Unsure how to implement the fix/feature
- [x] Difficulty understanding the codebase
- [ ] Other

### Reproducer

https://stackblitz.com/edit/qp6p6ewi?file=src%2FApp.vue

### Environment

Chrome on macos

### Vue version

3.5.13

### PrimeVue version

4.3.1

### Steps to reproduce the behavior

Just visit official site

### Expected behavior

Just works

**Comment by prabinsh** [comment]
I didn't have any issue with the reorder. Can you please explain behavior you are observing?

**Comment by AlexBindevald** [comment]
I have the same problem in official website and in my project. Worked correctly in 4.1.1 version.

**Comment by AlexBindevald** [comment]
probably this commit broke it https://github.com/primefaces/primevue/commit/c2a5378b9d2dded8fe253429f233cbafffc1845f

**Comment by AxelRothe** [comment]
Reorder is broken for me too. Doesn't work on the official website or my repos.

**Comment by ashokgelal** [comment]
Definitely broken

**Comment by liuchunlei-jpg** [comment]
> I didn't have any issue with the reorder. Can you please explain behavior you are observing?

Row drag sorting does not work

**Comment by liuchunlei-jpg** [comment]
Found the point: https://github.com/primefaces/primeuix/pull/46

**Comment by brecht-vermeersch** [comment]
Temporary workaround

```json
// package.json
  "resolutions": {
    "@primeuix/utils": "0.4.1"
  }
```

**Comment by 1Map** [comment]
@brecht-vermeersch In my case I also had to add @primeuix/styled:

```
  "resolutions": {
    "@primeuix/utils": "0.4.1",
    "@primeuix/styled": "0.4.1"
  },
```

**Comment by Aternix12** [comment]
> [@brecht-vermeersch](https://github.com/brecht-vermeersch) In my case I also had to add @primeuix/styled:
> 
> ```
>   "resolutions": {
>     "@primeuix/utils": "0.4.1",
>     "@primeuix/styled": "0.4.1"
>   },
> ```

This worked for me, nuxt3.

**Comment by liuchunlei-jpg** [comment]
> [@brecht-vermeersch](https://github.com/brecht-vermeersch) [@Aternix12](https://github.com/Aternix12) This workaround now suddenly does not work anymore in the latest 4.3.2

another a workaround

```vue
    <DataTable :value="" @rowReorder="onRowReorder">
        <Column #body="slotProps">
            <div class="cursor-move" draggable="true">
                <span class="pi pi-align-justify"></span>
            </div>
        </Column>
    </DataTable>
```

**Comment by tugcekucukoglu** [comment]
Fixed with https://github.com/primefaces/primeuix/pull/46

**Comment by 1Map** [comment]
@tugcekucukoglu Thanks, also remember to fix the reordering of treetable rows while you are busy with reordering of datatable rows.

**Comment by AxelRothe** [comment]
@tugcekucukoglu thank you very much for fixing this. It was an essential feature in one of my applications.

**Comment by desert-dionysus** [comment]
sorry to be that guy, but I'm struggling a bit to implement the fix described above.  

despite adding both @primeuix/utils and @primeuix/styled at both version 0.4.1 and 0.5.0 in my package.json, my Primevue components (in Primevue Styled mode) lose their styling, and the drag issue seems to still persist.

Not sure if I'm just doing something dumb around the primeuix packages, still fairly new to PV

**Comment by desert-dionysus** [comment]
> sorry to be that guy, but I'm struggling a bit to implement the fix described above.

disregard the above, I was able to get it working, interestingly by rolling back to the last working version, then stepping forward one release at a time and testing. In the end it worked with latest version.  Only change seems to have been my yarn.lock file being updated from @primeuix/utils@npm 0.5.1 to 0.5.2, unclear why this change wasn't reflected previously, but it works now.  Leaving this here in case it helps another knucklehead as lost as I was.
