### ISSUE TITLE
Primevue 2 dismissableMask=true not working when clicking outside the modal

### ISSUE THREAD

**Issue by kelvinabella** [primefaces/primevue#741]
Code can be seen here https://codesandbox.io/s/mystifying-shaw-080f3?file=/src/App.vue

**Comment by linh0801** [comment]
the issue has not been solved in V2.3.0.  At Dialog.vue , line 131   "this.mask === event.tagert" , the mask is undefined @cagataycivici

**Comment by linh0801** [comment]
How can I to update this version  by  npm  , I can't found the  package of latest V2.x at  the npm  repository @cagataycivici  @tugcekucukoglu

**Comment by nebulade** [comment]
As far as I can tell this is also broken in version 3.1.1

**Comment by cagataycivici** [comment]
Works for me on 3.2.0-rc.1, will check for 2.x.

**Comment by nebulade** [comment]
I have tried 3.2.0-rc.1 now and it still does not work. However by accident I found that it works fine, but only if also `closable` is set to `true`. I didn't specify this, since I didn't want to see the close button in the top-right. 
Not sure why both properties are dependent on each other, but if that is intentional, maybe the docs could mention this.

**Comment by MiC11w** [comment]
still broken in version 3.3.5

**Comment by Nabeelaron** [comment]
still broken in verison 3.5.1 as well. Please look into this.
Thanks.

**Comment by tugcekucukoglu** [comment]
For 3.5.1, cannot replicate it. [https://codesandbox.io/s/cool-bash-p4w3g](https://codesandbox.io/s/cool-bash-p4w3g)

**Comment by SabinoWS** [comment]
Hello!

It will only work if you use also :modal="true"
Because modal false will block the background of modal, so you cant click do dismiss with :dismissableMask="true"

**Working example:**
```
<Dialog
    v-bind="$attrs"
    :visible="visible"
    :draggable="draggable"
    :modal="true"
    :dismissableMask="true"
  >
    Test content
  </Dialog>
```

**Comment by cagataycivici** [comment]
Works for 3.5.1;

https://codesandbox.io/s/cool-bash-p4w3g

Please create a new ticket with a code sandbox template demonstrating the issue.

**Comment by richardshergold** [comment]
Something to note: this doesn't work if you have :closable="false" specified

**Comment by askomarov** [comment]
@tugcekucukoglu it's still not working even in last release 4.3 )))
